server:
  port: 8081

spring:
  application:
    name: FileUploader
  output:
    ansi:
      enabled: ALWAYS
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  dataSource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  Jpa:
    hibernate:
      ddl-auto: update

info:
  name: FileUploader

logging:
  file: logfile/fileuploader.log
  
